### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pyr0hu** [kiralyta/ntak-php#5]
Hey, 

first of all, thanks for the package, great work so far!

I've noticed that there is no license attached to the repo and as this NTAK misery usually handled by companies developing integrations, it would be nice to decide on a license for the library so the legal departments would be happy (or not, based on what kind of license you choose)

My recommendation would be a MIT one tbh.

**Comment by kiralyta** [comment]
Thanks for the recommendation, I added the MIT license to the package
